apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec: 
  replicas: 1
  selector:
    matchLabels:  # how deployments will fiind the pods
      app: auth
  template:
    metadata: 
      labels:
        app: auth   #this lable applied to pod, pod name will be this 
    spec:
      containers: 
        - name: auth
          image: kunaljk/auth       
          env: 
            - name: JWT_KEY #created this using $kubectl create secret generic jwt-secret --from-literal=JWT_KEY=asfd
              valueFrom: 
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY







---

apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector: 
    app: auth   #which pod governs access to, find pod with label of auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
     