apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-depl
spec: 
  replicas: 1
  selector:
    matchLabels:  # how deployments will fiind the pods
      app: orders
  template:
    metadata: 
      labels:
        app: orders   #this lable applied to pod, pod name will be this 
    spec:
      containers: 
        - name: orders
          image: kunaljk/orders       
          env:
            - name: NATS_CLUSTER_ID
              value: ticketing 
            - name: NATS_URL
              value: 'https://nats-srv:4222'
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name  
            - name: MONGO_URI
              value: 'mongodb://orders-mongo-srv:27017/orders'
            - name: JWT_KEY #created this using $kubectl create secret generic jwt-secret --from-literal=JWT_KEY=asfd
              valueFrom: 
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY







---

apiVersion: v1
kind: Service
metadata:
  name: orders-srv
spec:
  selector: 
    app: orders   #which pod governs access to, find pod with label of orders
  ports:
    - name: orders
      protocol: TCP
      port: 3000
      targetPort: 3000
     