name: deploy-orders

on:
  push:
    branches:
      - main
    paths:
      - "orders/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd orders && docker build -t kunaljk/orders .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      - run: docker push kunaljk/orders
    #   - uses: digitalocean/actions-doctl@v2
    #     with:
          # token: ${{secrets.DIGITAL_OCEAN_ACCESS_TOKEN}}
    #   - run: doctl kubernetes cluster kubeconfig save <kubernetes_cluster_name>
    #   - run: kubectl rollout restart deployment orders-depl
